/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 863c297d6831a953d48ec8dba8d2bad5)
interface __BaseEnv_Env {
  ASSET: Fetcher;
  TURSO_DB_URL: string;
  TURSO_DB_AUTH_TOKEN: string;
  UNSPLASH_ACCESS_KEY: string;
}
declare namespace Cloudflare {
  interface ProductionEnv {
    ASSET: Fetcher;
    TURSO_DB_URL: string;
    TURSO_DB_AUTH_TOKEN: string;
    UNSPLASH_ACCESS_KEY: string;
  }
  interface PreviewEnv {
    ASSET: Fetcher;
    TURSO_DB_URL: string;
    TURSO_DB_AUTH_TOKEN: string;
    UNSPLASH_ACCESS_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "TURSO_DB_URL" | "TURSO_DB_AUTH_TOKEN" | "UNSPLASH_ACCESS_KEY">
  > {}
}
