import { component$ } from "@qwik.dev/core";
import type { DocumentHead } from "@qwik.dev/router";
import licenses from "~/data/third-party-licenses.json";

// Generated by `pnpm sync:licenses` from both repos' direct dependencies
// (see scripts/sync-licenses.ts) — rerun it after a dependency change
// rather than editing the JSON.

// Hosted services, not libraries: no license to list, but what Tuxery
// runs on is worth knowing. Kept by hand — they change rarely.
const SERVICES = [
  {
    name: "Cloudflare Workers",
    role: "hosts and serves this website",
    url: "https://workers.cloudflare.com",
  },
  {
    name: "Turso",
    role: "the database the website reads the catalog from",
    url: "https://turso.tech",
  },
  {
    name: "GitHub",
    role: "code, issues, CI and the source caches",
    url: "https://github.com/tuxery",
  },
  { name: "Unsplash", role: "the header's background photos", url: "https://unsplash.com" },
];

export default component$(() => {
  return (
    <div class="flex flex-col gap-8 max-w-3xl">
      <div>
        <h1 class="text-3xl font-bold mb-2">Third-party licenses</h1>
        <p class="text-base-content/70">
          The open source software Tuxery is built with — this website, the data pipeline behind it,
          and the tools used to develop both — with each project's license. Only direct dependencies
          are listed; theirs come with their own license files. Tuxery's own license is on the{" "}
          <a href="/docs/license/" class="link link-primary">
            License
          </a>{" "}
          page.
        </p>
      </div>

      {licenses.groups.map((group) => (
        <section key={group.id} class="flex flex-col gap-2">
          <h2 class="text-lg font-semibold">{group.title}</h2>
          <p class="text-sm text-base-content/70">{group.description}</p>
          <div class="overflow-x-auto">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>Package</th>
                  <th>Version</th>
                  <th>License</th>
                </tr>
              </thead>
              <tbody>
                {group.packages.map((pkg) => (
                  <tr key={pkg.name}>
                    <td>
                      <a href={pkg.url} target="_blank" rel="noopener" class="link link-primary">
                        {pkg.name}
                      </a>
                    </td>
                    <td class="font-mono text-xs">{pkg.version}</td>
                    <td>{pkg.license}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      ))}

      <section class="flex flex-col gap-2">
        <h2 class="text-lg font-semibold">Services</h2>
        <p class="text-sm text-base-content/70">
          Not software Tuxery ships, but services it runs on.
        </p>
        <ul class="list-disc pl-5 text-base-content/80 flex flex-col gap-1">
          {SERVICES.map((service) => (
            <li key={service.name}>
              <a href={service.url} target="_blank" rel="noopener" class="link link-primary">
                {service.name}
              </a>{" "}
              — {service.role}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Third-party licenses — Tuxery",
  meta: [
    {
      name: "description",
      content:
        "The open source libraries and tools behind Tuxery's website and data pipeline, and their licenses.",
    },
  ],
};
